plugins { id 'com.android.application' }

android {
    namespace 'com.unknokable0.kadr'
    compileSdk 36

    defaultConfig {
        applicationId 'com.unknokable0.kadr'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.17.1'
}
